# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate internalization-analysis
#
name: internalization-analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - libgfortran==5.0.0.dev0  # pin version to avoid numpy ImportError
  # basic data science
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-image
  - openpyxl  # for reading excel in pandas

  # editor
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - jupyterlab_widgets
  - ipywidgets
  - pip:
    # jupyter lab code formatter
    - black
    - isort
    # report mode
    - jupyterlab-hide-code
    # read .czi images
    - bioio
    - bioio-czi